In [2]:
import os
import glob
import requests
import pandas as pd

# Define path to raw files directory
folder_path = os.path.join('data', 'raw')

# =====================================================================
# TASK 1: LOAD & INSPECT ALL LOCAL CSV FILES
# =====================================================================
print("==================================================")
print("      TASK 1: INSPECTING THE LOCAL DATASETS       ")
print("==================================================\n")

# Grab all available CSV files, ignoring previous live data downloads
csv_files = sorted(glob.glob(os.path.join(folder_path, '*.csv')))
csv_files = [f for f in csv_files if "live_nav" not in os.path.basename(f)]

print(f"🔍 Found {len(csv_files)} baseline datasets to inspect.\n")

for i, file_path in enumerate(csv_files, 1):
    file_name = os.path.basename(file_path)
    print("=" * 60)
    print(f"📄 DATASET {i}: {file_name}")
    print("=" * 60)
    
    try:
        df = pd.read_csv(file_path)
        
        print(f"1. SHAPE (Rows, Columns): {df.shape}")
        print("\n2. DATA TYPES (.dtypes):")
        print(df.dtypes)
        print("-" * 40)
        print("3. DATA PREVIEW (.head()):")
        display(df.head(5))
        
        # Scan for Missing Values / Duplicates
        missing_values = df.isnull().sum().sum()
        duplicate_rows = df.duplicated().sum()
        
        if missing_values > 0 or duplicate_rows > 0:
            print("\n⚠️ POTENTIAL ANOMALIES DETECTED:")
            if missing_values > 0:
                print(f"   - Found {missing_values} missing (NaN) values.")
                if "sip_inflows" in file_name:
                    print("     👉 Note: Missing values are the first 12 rows of 'yoy_growth_pct' due to missing 2021 baseline math.")
            if duplicate_rows > 0:
                print(f"   - Found {duplicate_rows} duplicate rows.")
        else:
            print("\n✅ Structure looks clean! No missing data or duplicates.")
            
    except Exception as e:
        print(f"❌ Error loading {file_name}: {e}")
    print("\n\n")

==================================================
      TASK 1: INSPECTING THE LOCAL DATASETS
==================================================

🔍 Found 10 baseline datasets to inspect.

============================================================
📄 DATASET 1: 01_fund_master.csv
============================================================
1. SHAPE (Rows, Columns): (40, 15)

2. DATA TYPES (.dtypes):
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 2: 02_nav_history.csv
============================================================
1. SHAPE (Rows, Columns): (46000, 3)

2. DATA TYPES (.dtypes):
amfi_code      int64
date             str
nav          float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 3: 03_aum_by_fund_house.csv
============================================================
1. SHAPE (Rows, Columns): (90, 5)

2. DATA TYPES (.dtypes):
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 4: 04_monthly_sip_inflows.csv
============================================================
1. SHAPE (Rows, Columns): (48, 6)

2. DATA TYPES (.dtypes):
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

⚠️ POTENTIAL ANOMALIES DETECTED:
   - Found 12 missing (NaN) values.
     👉 Note: Missing values are the first 12 rows of 'yoy_growth_pct' due to missing 2021 baseline math.



============================================================
📄 DATASET 5: 05_category_inflows.csv
============================================================
1. SHAPE (Rows, Columns): (144, 3)

2. DATA TYPES (.dtypes):
month                   str
category                str
net_inflow_crore    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 6: 06_industry_folio_count.csv
============================================================
1. SHAPE (Rows, Columns): (21, 6)

2. DATA TYPES (.dtypes):
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 7: 07_scheme_performance.csv
============================================================
1. SHAPE (Rows, Columns): (40, 19)

2. DATA TYPES (.dtypes):
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 8: 08_investor_transactions.csv
============================================================
1. SHAPE (Rows, Columns): (32778, 13)

2. DATA TYPES (.dtypes):
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 9: 09_portfolio_holdings.csv
============================================================
1. SHAPE (Rows, Columns): (322, 8)

2. DATA TYPES (.dtypes):
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 10: 10_benchmark_indices.csv
============================================================
1. SHAPE (Rows, Columns): (8050, 3)

2. DATA TYPES (.dtypes):
date               str
index_name         str
close_value    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

✅ Structure looks clean! No missing data or duplicates.

In [3]:
import os
import glob
import requests
import pandas as pd

# Define path to raw files directory
folder_path = os.path.join('data', 'raw')

# =====================================================================
# TASK 1: LOAD & INSPECT ALL LOCAL CSV FILES
# =====================================================================
print("==================================================")
print("      TASK 1: INSPECTING THE LOCAL DATASETS       ")
print("==================================================\n")

# Grab all available CSV files, ignoring previous live data downloads
csv_files = sorted(glob.glob(os.path.join(folder_path, '*.csv')))
csv_files = [f for f in csv_files if "live_nav" not in os.path.basename(f)]

print(f"🔍 Found {len(csv_files)} baseline datasets to inspect.\n")

for i, file_path in enumerate(csv_files, 1):
    file_name = os.path.basename(file_path)
    print("=" * 60)
    print(f"📄 DATASET {i}: {file_name}")
    print("=" * 60)
    
    try:
        df = pd.read_csv(file_path)
        
        print(f"1. SHAPE (Rows, Columns): {df.shape}")
        print("\n2. DATA TYPES (.dtypes):")
        print(df.dtypes)
        print("-" * 40)
        print("3. DATA PREVIEW (.head()):")
        display(df.head(5))
        
        # Scan for Missing Values / Duplicates
        missing_values = df.isnull().sum().sum()
        duplicate_rows = df.duplicated().sum()
        
        if missing_values > 0 or duplicate_rows > 0:
            print("\n⚠️ POTENTIAL ANOMALIES DETECTED:")
            if missing_values > 0:
                print(f"   - Found {missing_values} missing (NaN) values.")
                if "sip_inflows" in file_name:
                    print("     👉 Note: Missing values are the first 12 rows of 'yoy_growth_pct' due to missing 2021 baseline math.")
            if duplicate_rows > 0:
                print(f"   - Found {duplicate_rows} duplicate rows.")
        else:
            print("\n✅ Structure looks clean! No missing data or duplicates.")
            
    except Exception as e:
        print(f"❌ Error loading {file_name}: {e}")
    print("\n\n")


# =====================================================================
# TASK 2: FETCH LIVE NAV FROM API & SAVE AS RAW CSV
# =====================================================================
print("==================================================")
print("      TASK 2: FETCHING LIVE NAV FROM API         ")
print("==================================================\n")

scheme_id = "125497"  # HDFC Top 100 Direct Plan
api_url = f"https://api.mfapi.in/mf/{scheme_id}"

print(f"📡 Requesting real-time records from: {api_url}")

try:
    # 1. Fetch live JSON payload from API
    response = requests.get(api_url, timeout=15)
    response.raise_for_status()
    
    json_payload = response.json()
    metadata = json_payload.get('meta', {})
    historical_nav_data = json_payload.get('data', [])
    
    fund_name = metadata.get('scheme_name', 'HDFC Mutual Fund')
    print(f"✅ Success! Connected to API for: {fund_name}")
    print(f"📊 Retrieved {len(historical_nav_data)} total timeline entries.")
    
    # 2. Transform into a Pandas DataFrame
    df_live = pd.DataFrame(historical_nav_data)
    df_live['nav'] = pd.to_numeric(df_live['nav'])
    df_live['date'] = pd.to_datetime(df_live['date'], format='%d-%m-%Y')
    df_live = df_live.sort_values('date').reset_index(drop=True)
    
    # 3. Save directly to your data/raw folder
    output_filename = os.path.join(folder_path, f"{scheme_id}_live_nav.csv")
    df_live.to_csv(output_filename, index=False)
    print(f"💾 File safely saved to: {output_filename}")
    
    print(f"\n📊 Live NAV Dataset Final Shape: {df_live.shape}")
    print("\n📈 Top 5 rows of newly fetched data (.head()):")
    display(df_live.head(5))

except Exception as err:
    print(f"❌ API data processing sequence failed: {err}")

==================================================
      TASK 1: INSPECTING THE LOCAL DATASETS
==================================================

🔍 Found 10 baseline datasets to inspect.

============================================================
📄 DATASET 1: 01_fund_master.csv
============================================================
1. SHAPE (Rows, Columns): (40, 15)

2. DATA TYPES (.dtypes):
amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 2: 02_nav_history.csv
============================================================
1. SHAPE (Rows, Columns): (46000, 3)

2. DATA TYPES (.dtypes):
amfi_code      int64
date             str
nav          float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 3: 03_aum_by_fund_house.csv
============================================================
1. SHAPE (Rows, Columns): (90, 5)

2. DATA TYPES (.dtypes):
date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 4: 04_monthly_sip_inflows.csv
============================================================
1. SHAPE (Rows, Columns): (48, 6)

2. DATA TYPES (.dtypes):
month                            str
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

⚠️ POTENTIAL ANOMALIES DETECTED:
   - Found 12 missing (NaN) values.
     👉 Note: Missing values are the first 12 rows of 'yoy_growth_pct' due to missing 2021 baseline math.



============================================================
📄 DATASET 5: 05_category_inflows.csv
============================================================
1. SHAPE (Rows, Columns): (144, 3)

2. DATA TYPES (.dtypes):
month                   str
category                str
net_inflow_crore    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 6: 06_industry_folio_count.csv
============================================================
1. SHAPE (Rows, Columns): (21, 6)

2. DATA TYPES (.dtypes):
month                      str
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 7: 07_scheme_performance.csv
============================================================
1. SHAPE (Rows, Columns): (40, 19)

2. DATA TYPES (.dtypes):
amfi_code               int64
scheme_name               str
fund_house                str
category                  str
plan                      str
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade                str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 8: 08_investor_transactions.csv
============================================================
1. SHAPE (Rows, Columns): (32778, 13)

2. DATA TYPES (.dtypes):
investor_id               str
transaction_date          str
amfi_code               int64
transaction_type          str
amount_inr              int64
state                     str
city                      str
city_tier                 str
age_group                 str
gender                    str
annual_income_lakh    float64
payment_mode              str
kyc_status                str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 9: 09_portfolio_holdings.csv
============================================================
1. SHAPE (Rows, Columns): (322, 8)

2. DATA TYPES (.dtypes):
amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

✅ Structure looks clean! No missing data or duplicates.



============================================================
📄 DATASET 10: 10_benchmark_indices.csv
============================================================
1. SHAPE (Rows, Columns): (8050, 3)

2. DATA TYPES (.dtypes):
date               str
index_name         str
close_value    float64
dtype: object
----------------------------------------
3. DATA PREVIEW (.head()):

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

✅ Structure looks clean! No missing data or duplicates.



==================================================
      TASK 2: FETCHING LIVE NAV FROM API
==================================================

📡 Requesting real-time records from: https://api.mfapi.in/mf/125497
✅ Success! Connected to API for: SBI Small Cap Fund - Direct Plan - Growth
📊 Retrieved 3095 total timeline entries.
💾 File safely saved to: data\raw\125497_live_nav.csv

📊 Live NAV Dataset Final Shape: (3095, 2)

📈 Top 5 rows of newly fetched data (.head()):

        date      nav
0 2013-11-18  13.0894
1 2013-11-19  13.1068
2 2013-11-20  12.9549
3 2013-11-21  12.7957
4 2013-11-22  12.7775

In [1]:
import os
import time
import requests
import pandas as pd

# 1. Map names to the 5 requested scheme IDs
target_schemes = {
    "sbi_bluechip": "119551",
    "icici_bluechip": "120503",
    "nippon_large_cap": "118632",
    "axis_bluechip": "119092",
    "kotak_bluechip": "120841"
}

output_dir = os.path.join('data', 'raw')
os.makedirs(output_dir, exist_ok=True)

print("🚀 Starting bulk historical NAV acquisition pipeline...\n")

# 2. Iterate sequentially through each fund setup
for fund_name, scheme_id in target_schemes.items():
    api_url = f"https://api.mfapi.in/mf/{scheme_id}"
    print(f"📡 Requesting tracking records for: {fund_name.upper()} (ID: {scheme_id})")
    
    try:
        response = requests.get(api_url, timeout=15)
        response.raise_for_status()
        
        json_payload = response.json()
        historical_data = json_payload.get('data', [])
        
        if not historical_data:
            print(f"⚠️ Warning: No data returned for {fund_name}")
            continue
            
        # 3. Structural conversion into dataframes
        df = pd.DataFrame(historical_data)
        df['nav'] = pd.to_numeric(df['nav'])
        df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
        df = df.sort_values('date').reset_index(drop=True)
        
        # 4. Save to target raw directory
        filename = f"{scheme_id}_{fund_name}_live_nav.csv"
        file_path = os.path.join(output_dir, filename)
        df.to_csv(file_path, index=False)
        
        print(f"✅ Success! Saved {len(df)} days of records to: {file_path}")
        print(f"📈 Quick Preview: Start Date: {df['date'].min().strftime('%Y-%m-%d')} | Latest NAV: {df['nav'].iloc[-1]}")
        print("-" * 70)
        
        # 5. API Etiquette cooldown to protect the free endpoint
        time.sleep(1)
        
    except Exception as err:
        print(f"❌ Failed to acquire data for {fund_name}: {err}")
        print("-" * 70)

print("\n🎉 Bulk ingestion cycle complete! All datasets safely generated.")

🚀 Starting bulk historical NAV acquisition pipeline...

📡 Requesting tracking records for: SBI_BLUECHIP (ID: 119551)
✅ Success! Saved 3240 days of records to: data\raw\119551_sbi_bluechip_live_nav.csv
📈 Quick Preview: Start Date: 2013-01-02 | Latest NAV: 105.107
----------------------------------------------------------------------
📡 Requesting tracking records for: ICICI_BLUECHIP (ID: 120503)
✅ Success! Saved 3311 days of records to: data\raw\120503_icici_bluechip_live_nav.csv
📈 Quick Preview: Start Date: 2013-01-02 | Latest NAV: 103.8102
----------------------------------------------------------------------
📡 Requesting tracking records for: NIPPON_LARGE_CAP (ID: 118632)
✅ Success! Saved 3302 days of records to: data\raw\118632_nippon_large_cap_live_nav.csv
📈 Quick Preview: Start Date: 2013-01-02 | Latest NAV: 97.2456
----------------------------------------------------------------------
📡 Requesting tracking records for: AXIS_BLUECHIP (ID: 119092)
✅ Success! Saved 3569 days of records to: data\raw\119092_axis_bluechip_live_nav.csv
📈 Quick Preview: Start Date: 2012-12-31 | Latest NAV: 6168.4755
----------------------------------------------------------------------
📡 Requesting tracking records for: KOTAK_BLUECHIP (ID: 120841)
❌ Failed to acquire data for kotak_bluechip: HTTPSConnectionPool(host='api.mfapi.in', port=443): Read timed out. (read timeout=15)
----------------------------------------------------------------------

🎉 Bulk ingestion cycle complete! All datasets safely generated.

In [2]:
import os
import requests
import pandas as pd

# Target exactly the missing Kotak Bluechip scheme
fund_name = "kotak_bluechip"
scheme_id = "120841"
api_url = f"https://api.mfapi.in/mf/{scheme_id}"
output_dir = os.path.join('data', 'raw')

print(f"📡 Re-attempting connection for: {fund_name.upper()}...")

try:
    # Giving it a slightly longer timeout of 30 seconds just in case the server is sluggish
    response = requests.get(api_url, timeout=30)
    response.raise_for_status()
    
    json_payload = response.json()
    historical_data = json_payload.get('data', [])
    
    df = pd.DataFrame(historical_data)
    df['nav'] = pd.to_numeric(df['nav'])
    df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
    df = df.sort_values('date').reset_index(drop=True)
    
    filename = f"{scheme_id}_{fund_name}_live_nav.csv"
    file_path = os.path.join(output_dir, filename)
    df.to_csv(file_path, index=False)
    
    print(f"✅ Success! Saved {len(df)} days of historical records.")
    print(f"📈 Timeline ranges from {df['date'].min().strftime('%Y-%m-%d')} to today.")

except Exception as err:
    print(f"❌ Network retry failed: {err}")

📡 Re-attempting connection for: KOTAK_BLUECHIP...
✅ Success! Saved 3305 days of historical records.
📈 Timeline ranges from 2013-01-07 to today.

In [ ]:
import os
import pandas as pd

# Define files and their corresponding fund labels
files_to_merge = {
    "119551_sbi_bluechip_live_nav.csv": "SBI_Bluechip",
    "120503_icici_bluechip_live_nav.csv": "ICICI_Bluechip",
    "118632_nippon_large_cap_live_nav.csv": "Nippon_Large_Cap",
    "119092_axis_bluechip_live_nav.csv": "Axis_Bluechip",
    "120841_kotak_bluechip_live_nav.csv": "Kotak_Bluechip"
}

raw_dir = os.path.join('data', 'raw')
master_df = None

print("🔄 Starting data consolidation layer...")

for filename, fund_label in files_to_merge.items():
    file_path = os.path.join(raw_dir, filename)
    
    if os.path.exists(file_path):
        # Read the file and parse dates
        df = pd.read_csv(file_path)
        df['date'] = pd.to_datetime(df['date'])
        
        # Keep only date and nav, renaming nav to the specific fund name
        df = df[['date', 'nav']].rename(columns={'nav': fund_label})
        
        # Merge sequentially
        if master_df is None:
            master_df = df
        else:
            master_df = pd.merge(master_df, df, on='date', how='outer')
            
        print(f"🔹 Integrated {fund_label}")

# Sort from oldest to newest dates
master_df = master_df.sort_values('date').reset_index(drop=True)

# Fill missing values (weekends/holidays) using Forward Fill
master_df = master_df.ffill()

# Save to your 'processed' data folder
processed_dir = os.path.join('data', 'processed')
os.makedirs(processed_dir, exist_ok=True)
output_path = os.path.join(processed_dir, 'consolidated_large_cap_nav.csv')
master_df.to_csv(output_path, index=False)

print(f"\n🎉 Master dataset successfully created at: {output_path}")
print(f"📊 Dimensions: {master_df.shape[0]} rows x {master_df.shape[1]} columns")
master_df.tail(10)

🔄 Starting data consolidation layer...